version: '3.8'
services:
  postgres_db:
    image:  postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./db/migrations/postgres.session.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      LANGUAGE: ru_RU.UTF-8
      POSTGRES_USER:  "root"
      POSTGRES_PASSWORD:  "root"
      POSTGRES_DB: "api-hydroposts"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
